dataset_renames: {}
datasets:
  selected:
  - fri
environments: {}
evaluation:
  selected:
  - adaface_optimized
  - arcface
  - swinface
  - deepface_vggface
evaluation_renames: {}
logs_dir: logs
result_dir: results
root_dir: root_dir
technique_renames: {}
techniques:
  args: {}
  selected:
  - validation
  - pixelize
  - blur
visualization:
  selections: []
