dataset_renames: {}
datasets:
  selected:
  - celeba-test_aligned
environments: {}
evaluation:
  selected:
  - adaface_optimized
  - arcface
  - ssim
  - lpips
  - swinface
  - dan
evaluation_renames: {}
logs_dir: logs
result_dir: results
root_dir: root_dir
technique_renames: {}
techniques:
  args: {}
  selected:
  - blur
  - pixelize
visualization:
  selections: []
